<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find sct_description)/urdf/common/sct_mini_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="base_x_size" value="0.6200000"/>
    <xacro:property name="base_y_size" value="0.585000"/>
    <xacro:property name="base_z_size" value="0.235000"/>

    <xacro:property name="wheel_radius" value="0.08"/>

    <xacro:property name="wheel_track" value="0.416503"/>
    <xacro:property name="wheel_base" value="0.463951"/>
    <xacro:property name="wheel_offset_z" value="-0.100998"/>

    <xacro:macro name="chassis" params="use_sim:=false">
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 -1.5707"/>
                <geometry>
                    <mesh filename="package://sct_description/meshes/scout/base_link.dae"/>
                </geometry>
            </visual>
<!--            <visual>-->
<!--                <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>-->
<!--                <geometry>-->
<!--                    <mesh filename="package://sct_description/meshes/scout/base_link.stl" scale="0.001 0.001 0.001"/>-->
<!--                </geometry>-->
<!--            </visual>-->
            <visual>
                <origin xyz="0 0 0.15" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://sct_description/meshes/scout/upper_shell.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
                </geometry>
            </collision>
        </link>

        <link name="inertial_link">
            <inertial>
                <mass value="50"/>
                <origin xyz="0.0 0.0 0.0"/>
                <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465"/>
            </inertial>
        </link>

        <joint name="inertial_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="inertial_link"/>
        </joint>

        <xacro:sct_mini_wheel prefix="left_front" connected_to="base_link"
                     wheel_x_offset="${wheel_base/2}" wheel_y_offset="${wheel_track/2}"
                     wheel_z_offset="${wheel_offset_z}" rotation_degree="${-pi/2}" rotation_ori="${1}"/>
        <xacro:sct_mini_wheel prefix="left_rear" connected_to="base_link"
                              wheel_x_offset="${-wheel_base/2}" wheel_y_offset="${wheel_track/2}"
                              wheel_z_offset="${wheel_offset_z}" rotation_degree="${-pi/2}" rotation_ori="${1}"/>

        <xacro:sct_mini_wheel prefix="right_front" connected_to="base_link"
                     wheel_x_offset="${wheel_base/2}" wheel_y_offset="${-wheel_track/2}"
                     wheel_z_offset="${wheel_offset_z}" rotation_degree="${pi/2}" rotation_ori="${-1}"/>
        <xacro:sct_mini_wheel prefix="right_rear" connected_to="base_link"
                     wheel_x_offset="${-wheel_base/2}" wheel_y_offset="${-wheel_track/2}"
                     wheel_z_offset="${wheel_offset_z}" rotation_degree="${pi/2}" rotation_ori="${-1}"/>

        <!-- those wheel transmission useless when don't use ros-control   -->
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="1"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="1"/>
        <xacro:wheel_transmission prefix="left_rear" mechanical_reduction="1"/>
        <xacro:wheel_transmission prefix="right_rear" mechanical_reduction="1"/>

<!--        <xacro:if value="$(arg use_sim)">-->
<!--            <gazebo>-->
<!--                <plugin name="sct_chassis_sim" filename="libsct_chassis_sim.so">-->
<!--                    <updateRate>50.0</updateRate>-->
<!--                    <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>-->
<!--                    <leftFrontTransmission>1.0</leftFrontTransmission>-->

<!--                    <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>-->
<!--                    <rightFrontTransmission>-1.0</rightFrontTransmission>-->

<!--                    <leftRearJoint>left_rear_wheel_joint</leftRearJoint>-->
<!--                    <leftRearTransmission>1.0</leftRearTransmission>-->

<!--                    <rightRearJoint>right_rear_wheel_joint</rightRearJoint>-->
<!--                    <rightRearTransmission>-1.0</rightRearTransmission>-->

<!--                    <wheelTrack>${wheel_track}</wheelTrack>-->
<!--                    <wheelRadius>${wheel_radius}</wheelRadius>-->
<!--                    <torque>20</torque>-->
<!--                    <commandTopic>cmd_vel</commandTopic>-->

<!--                    <covariance_x>0.0001</covariance_x>-->
<!--                    <covariance_y>0.0001</covariance_y>-->
<!--                    <covariance_yaw>0.0001</covariance_yaw>-->
<!--                </plugin>-->
<!--            </gazebo>-->
<!--        </xacro:if>-->

    </xacro:macro>

</robot>
